RDM-12681 - Added SearchParty tab to XLS, fields need populating
hmcts/ccd-test-definitions pull request #5
Opened 2021-08-04 10:21 UTC by sullivangareth

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-12681

### Change description ###

Add new xlsx files for def store automated tests that test import of def fiels containing SearchParty tab

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-08-04 10:22 UTC, sullivangareth commented
Marked as draft, need further 3A call to walkthrough valid values

2021-08-16 09:45 UTC, mattnayler requested changes
To avoid confusion, can you unhide the other tabs in the BEFTA_Master_Definition files.  (including the invalids).

2021-08-16 10:20 UTC, mattnayler approved these changes
LGTM 👍

2021-08-16 10:31 UTC, smathangi approved these changes

2021-08-16 10:39 UTC, merged